#!/usr/bin/env python3
import sys

VERSION = "0.1.0"


def main():
    args = sys.argv[1:]

    if "--version" in args:
        print(f"mytools {VERSION}")
        sys.exit(0)

    print("usage: mytools --version", file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
